# Generated by roxytest: Do not edit by hand!

# File R/convert_custom.R: @testexamples

test_that("Function convert_custom() @ L21", {
  
  dt <- data.table::data.table(UpperCase = LETTERS[1:5], LowerCase = letters[1:5])
  dt
  x <- convert_custom(c("B", "C", "E", "E", "FF"), from = "UpperCase", to = "LowerCase", dt = dt)
  x
  expect_is(dt, "data.frame")
  expect_equal(x, c("b", "c", "e", "e", NA))
})

