# Generated by roxytest: Do not edit by hand!

context("File R/convert_icgc.R: @testexamples")

test_that("Function convert_icgc() @ L25", {


  x <- convert_icgc("SP29019")
  x


  if (!is.null(x)) expect_equal(x, "DO13695")
  if (!is.null(x)) expect_error(convert_pcawg("SA170678"))
  if (!is.null(x)) expect_error(convert_icgc("SP29019", from = "icgc_specimen_id", to = "icgc_specimen_id"))
})

