# Generated by roxytest: Do not edit by hand!

# File R/convert_pcawg.R: @testexamples

test_that("Function convert_pcawg() @ L36", {
  
  x <- convert_pcawg("SP1677")
  x
  
  y <- convert_pcawg("DO804",
    from = "icgc_donor_id",
    to = "icgc_specimen_id", multiple = TRUE
  )
  y
  
  expect_equal(x, "DO804")
  expect_error(convert_pcawg("SA5213"))
  expect_error(convert_icgc("SP1677", from = "icgc_specimen_id", to = "icgc_specimen_id"))
  expect_error(convert_icgc("SP1677", from = "icgc_specimen_id", to = "xx"))
  expect_is(y, "data.table")
})

